# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'LOKiOSDemo' do
pod 'RoutingHTTPServer', '~> 1.0'
pod 'PocketSocket', '~> 0.6.4'
end

target 'LOKiOSDemoTests' do

end

target 'LOKiOSDemoUITests' do

end

